### PR TITLE
Stats of the top langs coded by you

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
If you got projects contributed by other people/not coded by you/unity,godot files, please let me know those langs and I will hide those langs from showing in this chart.

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
I dont think the stats apply for forks, but i'm unsure.

**Comment by TechStudent10** [comment]
> If you got projects contributed by other people/not coded by you/unity,godot files, please let me know those langs and I will hide those langs from showing in this chart.

The only one is "Assembly".

> I dont think the stats apply for forks, but i'm unsure.

Apparently they do. I forked a repo that has Assembly in it.

**Comment by KendallDoesCoding** [comment]
> > If you got projects contributed by other people/not coded by you/unity,godot files, please let me know those langs and I will hide those langs from showing in this chart.
> 
> The only one is "Assembly".
> 
> > I dont think the stats apply for forks, but i'm unsure.
> 
> Apparently they do. I forked a repo that has Assembly in it.

So, I should hide assembly?

**Comment by TechStudent10** [comment]
> > > If you got projects contributed by other people/not coded by you/unity,godot files, please let me know those langs and I will hide those langs from showing in this chart.
> > 
> > 
> > The only one is "Assembly".
> > > I dont think the stats apply for forks, but i'm unsure.
> > 
> > 
> > Apparently they do. I forked a repo that has Assembly in it.
> 
> So, I should hide assembly?

Yes please. I don't even know the basics haha

**Comment by KendallDoesCoding** [comment]
> > > > If you got projects contributed by other people/not coded by you/unity,godot files, please let me know those langs and I will hide those langs from showing in this chart.
> > > 
> > > 
> > > The only one is "Assembly".
> > > > I dont think the stats apply for forks, but i'm unsure.
> > > 
> > > 
> > > Apparently they do. I forked a repo that has Assembly in it.
> > 
> > 
> > So, I should hide assembly?
> 
> Yes please. I don't even know the basics haha

Done

**Comment by KendallDoesCoding** [comment]
> > If you got projects contributed by other people/not coded by you/unity,godot files, please let me know those langs and I will hide those langs from showing in this chart.
> 
> The only one is "Assembly".
> 
> > I dont think the stats apply for forks, but i'm unsure.
> 
> Apparently they do. I forked a repo that has Assembly in it.

Well, if it inculdes forks, for me I contribute one-five commits for most projects I fork so this wont be right, but for me its kinda what I code, first up is HTML so ig its kinda accurate?

**Comment by TechStudent10** [comment]
> > > > > If you got projects contributed by other people/not coded by you/unity,godot files, please let me know those langs and I will hide those langs from showing in this chart.
> > > > 
> > > > 
> > > > The only one is "Assembly".
> > > > > I dont think the stats apply for forks, but i'm unsure.
> > > > 
> > > > 
> > > > Apparently they do. I forked a repo that has Assembly in it.
> > > 
> > > 
> > > So, I should hide assembly?
> > 
> > 
> > Yes please. I don't even know the basics haha
> 
> Done

Thanks! Merging...

**Pull request merged**
