### PR TITLE
add youtube icon that if they tap will take them to your YT

### PR DESCRIPTION
**Pull request by KendallDoesCoding**

### CODE REVIEW

**Review by TechStudent10 — CHANGES_REQUESTED** [review]
it should be red

**Comment by KendallDoesCoding** [comment]
> it should be red

Ok, will work on that!

**Comment by KendallDoesCoding** [comment]
Closed accidently.

**Comment by KendallDoesCoding** [comment]
Done as requested!

**Review by KendallDoesCoding — COMMENTED** [review]
Sorry, forgot to remove it lol

**Comment by KendallDoesCoding** [comment]
Thanks :)!

**Pull request merged**
